// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAub1XtmAJzjGH9RWdm-OeJzVB-rA5KXIA',
    appId: '1:457192942922:web:79fb0f6326236d9efee5b3',
    messagingSenderId: '457192942922',
    projectId: 'back-fresh',
    authDomain: 'back-fresh.firebaseapp.com',
    storageBucket: 'back-fresh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDehqpnrSVo4micCJ1g7bXegXIXjFA9hKQ',
    appId: '1:457192942922:android:90e294040d81a873fee5b3',
    messagingSenderId: '457192942922',
    projectId: 'back-fresh',
    storageBucket: 'back-fresh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQFE8TfJL2bk5kdCb0aWiolkxxzGNdRVk',
    appId: '1:457192942922:ios:f2fe9cb1b3484041fee5b3',
    messagingSenderId: '457192942922',
    projectId: 'back-fresh',
    storageBucket: 'back-fresh.appspot.com',
    iosBundleId: 'com.example.freshFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQFE8TfJL2bk5kdCb0aWiolkxxzGNdRVk',
    appId: '1:457192942922:ios:f2fe9cb1b3484041fee5b3',
    messagingSenderId: '457192942922',
    projectId: 'back-fresh',
    storageBucket: 'back-fresh.appspot.com',
    iosBundleId: 'com.example.freshFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAub1XtmAJzjGH9RWdm-OeJzVB-rA5KXIA',
    appId: '1:457192942922:web:dcc16c34b6f1d7c8fee5b3',
    messagingSenderId: '457192942922',
    projectId: 'back-fresh',
    authDomain: 'back-fresh.firebaseapp.com',
    storageBucket: 'back-fresh.appspot.com',
  );
}
